<?php
namespace GoldSdk\Api;

use GuzzleHttp\Client;
use Oasis\SlimApp\SlimApp;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManager;
/**
 * Created by SlimApp.
 *
 * Date: 2019-01-07
 * Time: 10:40
 */

class Api extends SlimApp
{
    public function getHttpKernel()
    {
        return parent::getHttpKernel(); // TODO: Change the autogenerated stub
    }
    
    public function getValidator()
    {
        return $this->getHttpKernel()['Validator'];
    }
    /**
     * @return EntityManager
     */
    public function getEntityManager()
    {
        return $this->getService("em");
    }
    /**
     * @return Request
     */
    public function getRequest()
    {
        return $this->getHttpKernel()->getParameter('request');
    }
    
    public function getApiUri()
    {
        return $this->getParameter('app.url.apiurl');
    }
    
    public function getPanelUri()
    {
        return $this->getParameter('app.url.panelurl');
    }
    
    public function getClient()
    {
        return new Client();
    }
}

